In [70]:
from Convnets import ConvLayer, Pool
from NeuralNetwork import NeuralNetwork
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from TrainHelpers import get_mnist, train_on_optims, run_test
import NpAutograd as npa
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
class LeNet5:
    """Simple helper class so that I can easily create a LeNet5 model. Not fancy or advisable, but it gets the job done."""
    def __init__(self):
        self.conv1 = ConvLayer(kernel_size=5, in_channels=1, out_channels=6, padding=2, stride=1)
        self.pool1 = Pool(kernel_size=2, stride=2, type="avg")
        self.conv2 = ConvLayer(kernel_size=5, in_channels=6, out_channels=16, padding=0, stride=1)
        self.pool2 = Pool(kernel_size=2, stride=2, type="avg")
        self.nn = NeuralNetwork(input_size=16*5*5, output_size=10, hidden=[120, 84], activation=npa.sigmoid)

    def __call__(self, x:npa.Tensor):
        c1 = self.conv1(x)
        p1 = self.pool1(c1)
        c2 = self.conv2(p1)
        p2 = self.pool2(c2)
        return self.nn(p2.flatten())

In [71]:
train_data, train_labels, test_data, test_labels = get_mnist()
train_data = train_data.reshape(-1, 1, 28, 28)
test_data = test_data.reshape(-1, 1, 28, 28)

In [72]:
conv = ConvLayer(kernel_size=5, in_channels=1, out_channels=6, padding=2, stride=1)
pool = Pool(kernel_size=2, stride=2, type="avg")
multilayer = conv(train_data[:2])
pooled = pool(multilayer)
loss = pooled.sum(0)
loss.backward()

1.0 [[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]